## Wretched creatures in Wollestonecraft and Wollestonecraft Shelley

My initial exploration suggests a commonality in the Wollestonecraft mother and daughter: the appearance of the terms "wretch" and "creature". Let's explore this commonality.

In [1]:
import re
from collections import Counter
import pandas as pd
import spacy
from spacy.matcher import Matcher
nlp = spacy.load('en_core_web_lg')

In [2]:
from IPython.display import display

In [3]:
def clean_gutenberg_text(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        text = f.read()

    start_pattern = r"\*\*\*\s*START OF.*?\*\*\*"
    end_pattern = r"\*\*\*\s*END OF.*?\*\*\*"

    start_match = re.search(start_pattern, text, re.DOTALL | re.IGNORECASE)
    end_match = re.search(end_pattern, text, re.DOTALL | re.IGNORECASE)

    if not start_match or not end_match:
        raise ValueError("Could not locate Gutenberg boundaries.")

    cleaned = text[start_match.end():end_match.start()]

    return cleaned.strip()

In [4]:
maria_clean = clean_gutenberg_text('../corpuses/wollstonecraft-corpus/maria.txt')

In [5]:
def split_by_contents(text):
    """
    Split a Gutenberg text into sections using its CONTENTS page.

    Returns:
        dict[str, str]
    """

    # Find CONTENTS section
    contents_match = re.search(
        r"\n\s*CONTENTS\s*\n",
        text,
        re.IGNORECASE
    )

    if not contents_match:
        raise ValueError("Could not find CONTENTS section.")

    contents_start = contents_match.end()

    # Everything after CONTENTS
    remainder = text[contents_start:]

    lines = remainder.splitlines()

    titles = []
    first_title_pos = None

    # Collect non-blank lines until we encounter
    # the first title repeated in the body.
    for i, line in enumerate(lines):
        stripped = line.strip()

        if not stripped:
            continue

        titles.append(stripped)

        # Look ahead: if this title appears later surrounded
        # by blank lines, we've probably reached the body.
        pattern = (
            r"\n\s*\n\s*"
            + re.escape(stripped)
            + r"\s*\n"
        )

        m = re.search(pattern, remainder)

        if m and m.start() > 0:
            first_title_pos = m.start()
            break

    if first_title_pos is None:
        raise ValueError("Could not determine end of CONTENTS section.")

    contents_text = remainder[:first_title_pos]
    titles = [
        line.strip()
        for line in contents_text.splitlines()
        if line.strip()
    ]

    body = remainder[first_title_pos:]

    # Locate each title in the body
    sections = []

    for title in titles:
        pattern = (
            r"\n\s*\n\s*"
            + re.escape(title)
            + r"\s*\n"
        )

        m = re.search(pattern, body)

        if m:
            sections.append((title, m.start()))

    if not sections:
        raise ValueError("No section headings found in body.")

    # Slice text into sections
    result = {}

    for i, (title, start) in enumerate(sections):
        if i + 1 < len(sections):
            end = sections[i + 1][1]
        else:
            end = len(body)

        result[title] = body[start:end].strip()

    return result

In [6]:
maria_chapters_dict = split_by_contents(maria_clean)

In [7]:
maria_chapters_dict.keys()

dict_keys(['MARIA', 'PREFACE', 'AUTHOR’S PREFACE', 'CHAPTER 1', 'CHAPTER 2', 'CHAPTER 3', 'CHAPTER 4', 'CHAPTER 5', 'CHAPTER 6', 'CHAPTER 7', 'CHAPTER 8', 'CHAPTER 9', 'CHAPTER 10', 'CHAPTER 11', 'CHAPTER 12', 'CHAPTER 13', 'CHAPTER 14', 'APPENDIX', 'CHAPTER 15', 'CHAPTER 16', 'CHAPTER 17', 'CONCLUSION'])

In [8]:
del(maria_chapters_dict['MARIA'])
del(maria_chapters_dict['PREFACE'])

In [9]:
maria_chapters_dict.keys()

dict_keys(['AUTHOR’S PREFACE', 'CHAPTER 1', 'CHAPTER 2', 'CHAPTER 3', 'CHAPTER 4', 'CHAPTER 5', 'CHAPTER 6', 'CHAPTER 7', 'CHAPTER 8', 'CHAPTER 9', 'CHAPTER 10', 'CHAPTER 11', 'CHAPTER 12', 'CHAPTER 13', 'CHAPTER 14', 'APPENDIX', 'CHAPTER 15', 'CHAPTER 16', 'CHAPTER 17', 'CONCLUSION'])

In [10]:
def unwrap_gutenberg_paragraphs(text):
    """
    Remove Gutenberg line wrapping while preserving paragraphs.
    """

    # Normalize line endings
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Split into paragraphs
    paragraphs = re.split(r"\n\s*\n+", text)

    cleaned = []

    for para in paragraphs:
        # Replace internal newlines with spaces
        para = re.sub(r"\s*\n\s*", " ", para)

        # Collapse repeated spaces
        para = re.sub(r"\s+", " ", para)

        cleaned.append(para.strip())

    return "\n\n".join(cleaned)

In [11]:
maria_chapters_dict = {
    title: unwrap_gutenberg_paragraphs(text)
    for title, text in maria_chapters_dict.items()
}

In [12]:
def normalize_whitespace(text):
    """
    Convert all whitespace (spaces, tabs, newlines)
    into single spaces.
    """
    return " ".join(text.split())

In [13]:
maria_chapters_no_pars = {
    title: normalize_whitespace(text)
    for title, text in maria_chapters_dict.items()
}

In [14]:
wretch_pattern = [{"LEMMA": {"IN": ['wretch', 'wretched', 'creature']}}]
matcher = Matcher(nlp.vocab)
matcher.add("WRETCH-CREATURE", [wretch_pattern])

In [15]:
pd.set_option('display.max_colwidth', None)

In [16]:
def extract_emotion_matches(chapters_dict, matcher, nlp):
    match_data = []

    for chapter_number, chapter_text in chapters_dict.items():
        doc = nlp(chapter_text)
        matches = matcher(doc)

        for match_id, start, end in matches:
            span = doc[start:end]
            sentence = span.sent
            label = nlp.vocab.strings[match_id]
            lemma = span[0].lemma_
            cleaned_sentence = " ".join(sentence.text.strip().split())

            match_data.append({
                "chapter": chapter_number,
                "emotion": label,
                "lemma": lemma,
                "sentence": cleaned_sentence,
                "sentence_start_char": sentence.start_char,
                "sentence_end_char": sentence.end_char,
            })

    return pd.DataFrame(match_data)

In [17]:
maria_wretch_df = extract_emotion_matches(maria_chapters_no_pars, matcher, nlp)
maria_wretch_df

,chapter,emotion,lemma,sentence,sentence_start_char,sentence_end_char
0,CHAPTER 1,WRETCH-CREATURE,wretched,"Jemima (she had only a claim to a Christian name, which had not procured her any Christian privileges) could patiently hear of Maria’s confinement on false pretences; she had felt the crushing hand of power, hardened by the exercise of injustice, and ceased to wonder at the perversions of the understanding, which systematize oppression; but, when told that her child, only four months old, had been torn from her, even while she was discharging the tenderest maternal office, the woman awoke in a bosom long estranged from feminine emotions, and Jemima determined to alleviate all in her power, without hazarding the loss of her place, the sufferings of a wretched mother, apparently injured, and certainly unhappy.",10290,11007
1,CHAPTER 2,WRETCH-CREATURE,creature,"An insulated being, from the misfortune of her birth, she despised and preyed on the society by which she had been oppressed, and loved not her fellow-creatures, because she had never been beloved.",2581,2778
2,CHAPTER 2,WRETCH-CREATURE,wretch,"Maria was not permitted to walk in the garden; but sometimes, from her window, she turned her eyes from the gloomy walls, in which she pined life away, on the poor wretches who strayed along the walks, and contemplated the most terrific of ruins—that of a human soul.",4647,4914
3,CHAPTER 2,WRETCH-CREATURE,wretch,"Melancholy and imbecility marked the features of the wretches allowed to breathe at large; for the frantic, those who in a strong imagination had lost a sense of woe, were closely confined.",5979,6168
4,CHAPTER 2,WRETCH-CREATURE,wretch,"Her busy fancy pictured the misery of a fond heart, watching over a friend thus estranged, absent, though present—over a poor wretch lost to reason and the social joys of existence; and losing all consciousness of misery in its excess.",7010,7245
5,CHAPTER 2,WRETCH-CREATURE,wretch,"“They come,” said she, “perhaps, from a wretch condemned, like me, to reason on the nature of madness, by having wrecked minds continually under his eye; and almost to wish himself—as I do—mad, to escape from the contemplation of it.”",9006,9240
6,CHAPTER 2,WRETCH-CREATURE,wretch,"Thus shut out from human intercourse, and compelled to view nothing but the prison of vexed spirits, to meet a wretch in the same situation, was more surely to find a friend, than to imagine a countryman one, in a strange land, where the human voice conveys no information to the eager ear.",11353,11643
7,CHAPTER 2,WRETCH-CREATURE,wretch,"Several minutes elapsed before Maria could enquire respecting the rumour of the house (for this poor wretch was obviously not confined without a cause); and then Jemima could only tell her, that it was said, “she had been married, against her inclination, to a rich old man, extremely jealous (no wonder, for she was a charming creature); and that, in consequence of his treatment, or something which hung on her mind, she had, during her first lying-in, lost her senses.”",14732,15204
8,CHAPTER 2,WRETCH-CREATURE,creature,"Several minutes elapsed before Maria could enquire respecting the rumour of the house (for this poor wretch was obviously not confined without a cause); and then Jemima could only tell her, that it was said, “she had been married, against her inclination, to a rich old man, extremely jealous (no wonder, for she was a charming creature); and that, in consequence of his treatment, or something which hung on her mind, she had, during her first lying-in, lost her senses.”",14732,15204
9,CHAPTER 3,WRETCH-CREATURE,wretch,"Thinking it selfish to dwell on her own sufferings, when in the midst of wretches, who had not only lost all that endears life, but their very selves, her imagination was occupied with melancholy earnestness to trace the mazes of misery, through which so many wretches must have passed to this gloomy receptacle of disjointed souls, to the grand source of human corruption.",2595,2968
10,CHAPTER 3,WRETCH-CREATURE,wretch,"Thinking it selfish to dwell on her own sufferings, when in the midst of wretches, who had not only lost all that endears life, but their very selves, her imagination was occupied with melancholy earnestness to trace the mazes of misery, through which so many wretches must have passed to this gloomy receptacle of disjointed souls, to the grand source of human corruption.",2595,2968
11,CHAPTER 3,WRETCH-CREATURE,creature,"I was taught to love by a creature I am ashamed to mention; and the other women with whom I afterwards became intimate, were of a class of which you can have no knowledge.",8173,8344
12,CHAPTER 4,WRETCH-CREATURE,wretched,"The youths who are satisfied with the ordinary pleasures of life, and do not sigh after ideal phantoms of love and friendship, will never arrive at great maturity of understanding; but if these reveries are cherished, as is too frequently the case with women, when experience ought to have taught them in what human happiness consists, they become as useless as they are wretched.",1992,2372
13,CHAPTER 4,WRETCH-CREATURE,creature,"She seemed indeed to breathe more freely; the cloud of suspicion cleared away from her brow; she felt herself, for once in her life, treated like a fellow-creature.",6938,7102
14,CHAPTER 5,WRETCH-CREATURE,wretched,"Death came not at her call; yet sorrow, and the methods she adopted to conceal her condition, still doing the work of a house-maid, had such an effect on her constitution, that she died in the wretched garret, where her virtuous mistress had forced her to take refuge in the very pangs of labour, though my father, after a slight reproof, was allowed to remain in his place—allowed by the mother of six children, who, scarcely permitting a footstep to be heard, during her month’s indulgence, felt no sympathy for the poor wretch, denied every comfort required by her situation.",979,1557
15,CHAPTER 5,WRETCH-CREATURE,wretch,"Death came not at her call; yet sorrow, and the methods she adopted to conceal her condition, still doing the work of a house-maid, had such an effect on her constitution, that she died in the wretched garret, where her virtuous mistress had forced her to take refuge in the very pangs of labour, though my father, after a slight reproof, was allowed to remain in his place—allowed by the mother of six children, who, scarcely permitting a footstep to be heard, during her month’s indulgence, felt no sympathy for the poor wretch, denied every comfort required by her situation.",979,1557
16,CHAPTER 5,WRETCH-CREATURE,creature,"No wonder then, treated like a creature of another species, that I began to envy, and at length to hate, the darling of the house.",4270,4400
17,CHAPTER 5,WRETCH-CREATURE,creature,"I had been introduced as an object of abhorrence into the family; as a creature of whom my step-mother, though she had been kind enough to let me live in the house with her own child, could make nothing.",7038,7241
18,CHAPTER 5,WRETCH-CREATURE,wretch,"I was described as a wretch, whose nose must be kept to the grinding stone—and it was held there with an iron grasp.",7242,7358
19,CHAPTER 5,WRETCH-CREATURE,creature,"Yes; I had not even the chance of being considered as a fellow-creature—yet all the people with whom I lived, brutalized as they were by the low cunning of trade, and the despicable shifts of poverty, were not without bowels, though they never yearned for me.",9579,9838
20,CHAPTER 5,WRETCH-CREATURE,creature,"“Nobody yet suspected me, because they had been accustomed to view me as a creature of another species.",11776,11879
21,CHAPTER 5,WRETCH-CREATURE,wretch,"She tore off my cap, scratched, kicked, and buffetted me, till she had exhausted her strength, declaring, as she rested her arm, ‘that I had wheedled her husband from her.—But, could any thing better be expected from a wretch, whom she had taken into her house out of pure charity?’",12448,12730
22,CHAPTER 5,WRETCH-CREATURE,wretch,"This plea came home to his reason, who had been sobered by his wife’s rage, the fury of which fell on him when I was out of her reach, and he sent the boy to me with half-a-guinea, desiring him to conduct me to a house, where beggars, and other wretches, the refuse of society, nightly lodged.",14002,14295
23,CHAPTER 5,WRETCH-CREATURE,wretch,"“With this wretch I went into the neighbouring streets to beg, and my disconsolate appearance drew a few pence from the idle, enabling me still to command a bed; till, recovering from my illness, and taught to put on my rags to the best advantage, I was accosted from different motives, and yielded to the desire of the brutes I met, with the same detestation that I had felt for my still more brutal master.",15721,16129
24,CHAPTER 5,WRETCH-CREATURE,wretch,"You can scarcely conceive the tyranny exercised by these wretches: considering themselves as the instruments of the very laws they violate, the pretext which steels their conscience, hardens their heart.",17372,17575
25,CHAPTER 5,WRETCH-CREATURE,creature,"Not content with receiving from us, outlaws of society (let other women talk of favours) a brutal gratification gratuitously as a privilege of office, they extort a tithe of prostitution, and harrass with threats the poor creatures whose occupation affords not the means to silence the growl of avarice.",17576,17879
26,CHAPTER 5,WRETCH-CREATURE,creature,"Had he had any time for reflection, I am certain he would have left the little property in his power to me: but, attacked by the fatal apoplexy in town, his heir, a man of rigid morals, brought his wife with him to take possession of the house and effects, before I was even informed of his death,—‘to prevent,’ as she took care indirectly to tell me, ‘such a creature as she supposed me to be, from purloining any of them, had I been apprized of the event in time.’",22415,22881
27,CHAPTER 5,WRETCH-CREATURE,wretch,"Tears started in my eyes, burning tears; for there are situations in which a wretch is humbled by the contempt they are conscious they do not deserve.",23561,23711
28,CHAPTER 5,WRETCH-CREATURE,wretch,Poor wretch!,30526,30538
29,CHAPTER 5,WRETCH-CREATURE,wretch,I determined not to live with the wretch.,31634,31675
30,CHAPTER 5,WRETCH-CREATURE,wretched,"If those well-meaning people who exclaim against beggars, were acquainted with the treatment the poor receive in many of these wretched asylums, they would not stifle so easily involuntary sympathy, by saying that they have all parishes to go to, or wonder that the poor dread to enter the gloomy walls.",35065,35368
31,CHAPTER 5,WRETCH-CREATURE,wretch,"A coffin carried on the shoulders of three or four ill-looking wretches, whom the imagination might easily convert into a band of assassins, hastening to conceal the corpse, and quarrelling about the prey on their way.",35744,35962
32,CHAPTER 5,WRETCH-CREATURE,wretched,"I know it is of little consequence how we are consigned to the earth; but I am led by this brutal insensibility, to what even the animal creation appears forcibly to feel, to advert to the wretched, deserted manner in which they died.”",35963,36198
33,CHAPTER 5,WRETCH-CREATURE,wretch,"“I agreed to accompany him; and four years have I been attendant on many wretches, and”—she lowered her voice,—“the witness of many enormities.",37345,37488
34,CHAPTER 5,WRETCH-CREATURE,creature,Still what should induce me to be the champion for suffering humanity?—Who ever risked any thing for me?—Who ever acknowledged me to be a fellow-creature?”,37654,37809
35,CHAPTER 7,WRETCH-CREATURE,creature,"“I had two mattresses on my bed; what did I want with two, when such a worthy creature must lie on the ground?",19088,19198
36,CHAPTER 8,WRETCH-CREATURE,wretch,"“Had this truly generous man mentioned his intention to me, I should have insisted on a thousand pounds being settled on each of my sisters; George would have contested; I should have seen his selfish soul; and—gracious God! have been spared the misery of discovering, when too late, that I was united to a heartless, unprincipled wretch.",7122,7460
37,CHAPTER 9,WRETCH-CREATURE,creature,"To such a degree, in fact, did his cold, reserved manner affect me, that, after spending some days with him alone, I have imagined myself the most stupid creature in the world, till the abilities of some casual visitor convinced me that I had some dormant animation, and sentiments above the dust in which I had been groveling.",5243,5570
38,CHAPTER 10,WRETCH-CREATURE,wretched,"Esteem will often supply the place of love; and prevent a woman from being wretched, though it may not make her happy.",13810,13928
39,CHAPTER 12,WRETCH-CREATURE,creature,"“They had excited sensations similar to those I have felt, in viewing the squalid inhabitants of some of the lanes and back streets of the metropolis, mortified at being compelled to consider them as my fellow-creatures, as if an ape had claimed kindred with me.",6100,6362
40,CHAPTER 14,WRETCH-CREATURE,wretch,"All I know is, that she must have quitted the chaise, shameless wretch!",3513,3584
41,CHAPTER 14,WRETCH-CREATURE,creature,"How could a creature in a female form see me caress thee, and steal thee from my arms!",3630,3716
42,CHAPTER 14,WRETCH-CREATURE,wretch,"A candle flaring in the socket, scarcely dispersed the darkness, though it displayed to me the ferocious countenance of the wretch who held me.",5503,5646
43,CHAPTER 16,WRETCH-CREATURE,creature,"[Godwin’s note] With Darnford she did not taste uninterrupted felicity; there was a volatility in his manner which often distressed her; but love gladdened the scene; besides, he was the most tender, sympathizing creature in the world.",6868,7103
44,CONCLUSION,WRETCH-CREATURE,creature,"Jemima seemed to enter—leading a little creature, that, with tottering footsteps, approached the bed.",2944,3045

In [18]:
frankenstein_clean = clean_gutenberg_text('../corpuses/shelley-corpus/frankenstein.txt')
frankenstein_chapters = split_by_contents(frankenstein_clean)
frankenstein_normalized = {
    title: normalize_whitespace(text)
    for title, text in frankenstein_chapters.items()
}

In [19]:
frankenstein_wretch_df = extract_emotion_matches(frankenstein_normalized, matcher, nlp)

In [20]:
frankenstein_wretch_df

,chapter,emotion,lemma,sentence,sentence_start_char,sentence_end_char
0,Letter 4,WRETCH-CREATURE,wretched,I never saw a man in so wretched a condition.,3418,3463
1,Letter 4,WRETCH-CREATURE,creature,"I never saw a more interesting creature: his eyes have generally an expression of wildness, and even madness, but there are moments when, if anyone performs an act of kindness towards him or does him any the most trifling service, his whole countenance is lighted up, as it were, with a beam of benevolence and sweetness that I never saw equalled.",4167,4514
2,Letter 4,WRETCH-CREATURE,creature,"He must have been a noble creature in his better days, being even now in wreck so attractive and amiable.",7124,7229
3,Letter 4,WRETCH-CREATURE,creature,How can I see so noble a creature destroyed by misery without feeling the most poignant grief?,7716,7810
4,Letter 4,WRETCH-CREATURE,creature,"“I agree with you,” replied the stranger; “we are unfashioned creatures, but half made up, if one wiser, better, dearer than ourselves—such a friend ought to be—do not lend his aid to perfectionate our weak and faulty natures.",10299,10525
...,...,...,...,...,...,...
112,Chapter 24,WRETCH-CREATURE,creature,"Urged by this view, I refused, and I did right in refusing, to create a companion for the first creature.",32370,32475
113,Chapter 24,WRETCH-CREATURE,wretched,"Miserable himself that he may render no other wretched, he ought to die.",32706,32778
114,Chapter 24,WRETCH-CREATURE,creature,"When I run over the frightful catalogue of my sins, I cannot believe that I am the same creature whose thoughts were once filled with sublime and transcendent visions of the beauty and the majesty of goodness.",40923,41132
115,Chapter 24,WRETCH-CREATURE,wretch,“But it is true that I am a wretch.,42176,42211
116,Chapter 24,WRETCH-CREATURE,wretch,"I shall quit your vessel on the ice raft which brought me thither and shall seek the most northern extremity of the globe; I shall collect my funeral pile and consume to ashes this miserable frame, that its remains may afford no light to any curious and unhallowed wretch who would create such another as I have been.",43185,43502

In [21]:
for _, row in frankenstein_wretch_df.iterrows():
    print(row['chapter'])
    print(row['lemma'])
    print(row['sentence'])
    print('-------------------')

Letter 4
wretched
I never saw a man in so wretched a condition.
-------------------
Letter 4
creature
I never saw a more interesting creature: his eyes have generally an expression of wildness, and even madness, but there are moments when, if anyone performs an act of kindness towards him or does him any the most trifling service, his whole countenance is lighted up, as it were, with a beam of benevolence and sweetness that I never saw equalled.
-------------------
Letter 4
creature
He must have been a noble creature in his better days, being even now in wreck so attractive and amiable.
-------------------
Letter 4
creature
How can I see so noble a creature destroyed by misery without feeling the most poignant grief?
-------------------
Letter 4
creature
“I agree with you,” replied the stranger; “we are unfashioned creatures, but half made up, if one wiser, better, dearer than ourselves—such a friend ought to be—do not lend his aid to perfectionate our weak and faulty natures.
-------------------
Letter 4
creature
I once had a friend, the most noble of human creatures, and am entitled, therefore, to judge respecting friendship.
-------------------
Chapter 1
creature
I was their plaything and their idol, and something better—their child, the innocent and helpless creature bestowed on them by Heaven, whom to bring up to good, and whose future lot it was in their hands to direct to happiness or misery, according as they fulfilled their duties towards me.
-------------------
Chapter 1
creature
When my father returned from Milan, he found playing with me in the hall of our villa a child fairer than pictured cherub—a creature who seemed to shed radiance from her looks and whose form and motions were lighter than the chamois of the hills.
-------------------
Chapter 4
creature
Every night I was oppressed by a slow fever, and I became nervous to a most painful degree; the fall of a leaf startled me, and I shunned my fellow creatures as if I had been guilty of a crime.
-------------------
Chapter 5
creature
It was already one in the morning; the rain pattered dismally against the panes, and my candle was nearly burnt out, when, by the glimmer of the half-extinguished light, I saw the dull yellow eye of the creature open; it breathed hard, and a convulsive motion agitated its limbs.
-------------------
Chapter 5
wretch
How can I describe my emotions at this catastrophe, or how delineate the wretch whom with such infinite pains and care I had endeavoured to form?
-------------------
Chapter 5
wretch
I started from my sleep with horror; a cold dew covered my forehead, my teeth chattered, and every limb became convulsed; when, by the dim and yellow light of the moon, as it forced its way through the window shutters, I beheld the wretch—the miserable monster whom I had created.
-------------------
Chapter 5
wretch
A mummy again endued with animation could not be so hideous as that wretch.
-------------------
Chapter 5
wretch
The porter opened the gates of the court, which had that night been my asylum, and I issued into the streets, pacing them with quick steps, as if I sought to avoid the wretch whom I feared every turning of the street would present to my view.
-------------------
Chapter 5
creature
I then reflected, and the thought made me shiver, that the creature whom I had left in my apartment might still be there, alive and walking about.
-------------------
Chapter 5
wretched
I afterwards learned that, knowing my father’s advanced age and unfitness for so long a journey, and how wretched my sickness would make Elizabeth, he spared them this grief by concealing the extent of my disorder.
-------------------
Chapter 6
creature
This benefit was fully repaid; Justine was the most grateful little creature in the world: I do not mean that she made any professions I never heard one pass her lips, but you could see by her eyes that she almost adored her protectress.
-------------------
Chapter 6
creature
Study had before secluded me from the intercourse of my fellow-creatures, and rendered me unsocial; but Clerval called forth the better feelings of my heart; he again taught me to love the aspect of nature, and the cheerful faces of children.
-------------------
Chapter 6
creature
A selfish pursuit had cramped and narrowed me, until your gentleness and affection warmed and opened my senses; I became the same happy creature who, a few years ago, loved and beloved by all, had no sorrow or care.
-------------------
Chapter 7
wretched
The picture appeared a vast and dim scene of evil, and I foresaw obscurely that I was destined to become the most wretched of human beings.
-------------------
Chapter 7
wretch
A flash of lightning illuminated the object, and discovered its shape plainly to me; its gigantic stature, and the deformity of its aspect more hideous than belongs to humanity, instantly informed me that it was the wretch, the filthy dæmon, to whom I had given life.
-------------------
Chapter 7
wretch
I had turned loose into the world a depraved wretch, whose delight was in carnage and misery; had he not murdered my brother?
-------------------
Chapter 7
creature
Who could arrest a creature capable of scaling the overhanging sides of Mont Salêve?
-------------------
Chapter 7
wretched
“She most of all,” said Ernest, “requires consolation; she accused herself of having caused the death of my brother, and that made her very wretched.
-------------------
Chapter 7
wretched
every one else believes in her guilt, and that made me wretched, for I knew that it was impossible: and to see every one else prejudiced in so deadly a manner rendered me hopeless and despairing.”
-------------------
Chapter 8
wretched
During the whole of this wretched mockery of justice I suffered living torture.
-------------------
Chapter 8
creature
It may therefore be judged indecent in me to come forward on this occasion, but when I see a fellow creature about to perish through the cowardice of her pretended friends, I wish to be allowed to speak, that I may say what I know of her character.
-------------------
Chapter 8
creature
During all that period she appeared to me the most amiable and benevolent of human creatures.
-------------------
Chapter 8
wretched
I relied on your innocence, and although I was then very wretched, I was not so miserable as I am now.”
-------------------
Chapter 8
wretch
Dear lady, I had none to support me; all looked on me as a wretch doomed to ignominy and perdition.
-------------------
Chapter 8
creature
She paused, weeping, and then continued, “I thought with horror, my sweet lady, that you should believe your Justine, whom your blessed aunt had so highly honoured, and whom you loved, was a creature capable of a crime which none but the devil himself could have perpetrated.
-------------------
Chapter 8
wretch
How sweet is the affection of others to such a wretch as I am!
-------------------
Chapter 8
wretched
Thus I might proclaim myself a madman, but not revoke the sentence passed upon my wretched victim.
-------------------
Chapter 9
creature
She was no longer that happy creature who in earlier youth wandered with me on the banks of the lake and talked with ecstasy of our future prospects.
-------------------
Chapter 9
creature
Everybody believed that poor girl to be guilty; and if she could have committed the crime for which she suffered, assuredly she would have been the most depraved of human creatures.
-------------------
Chapter 9
creature
I could not consent to the death of any human being, but certainly I should have thought such a creature unfit to remain in the society of men.
-------------------
Chapter 9
wretch
But even if I were condemned to suffer on the scaffold for the same crimes, I would not change places with such a wretch.”
-------------------
Chapter 9
wretched
These events have affected me, God knows how deeply; but I am not so wretched as you are.
-------------------
Chapter 10
wretch
I perceived, as the shape came nearer (sight tremendous and abhorred!) that it was the wretch whom I had created.
-------------------
Chapter 10
wretched
“All men hate the wretched; how, then, must I be hated, who am miserable beyond all living things!
-------------------
Chapter 10
creature
Yet you, my creator, detest and spurn me, thy creature, to whom thou art bound by ties only dissoluble by the annihilation of one of us.
-------------------
Chapter 10
wretched
Wretched devil!
-------------------
Chapter 10
creature
I am thy creature, and I will be even mild and docile to my natural lord and king if thou wilt also perform thy part, the which thou owest me.
-------------------
Chapter 10
creature
Remember that I am thy creature; I ought to be thy Adam, but I am rather the fallen angel, whom thou drivest from joy for no misdeed.
-------------------
Chapter 10
creature
Will no entreaties cause thee to turn a favourable eye upon thy creature, who implores thy goodness and compassion?
-------------------
Chapter 10
creature
You, my creator, abhor me; what hope can I gather from your fellow creatures, who owe me nothing?
-------------------
Chapter 10
creature
You accuse me of murder, and yet you would, with a satisfied conscience, destroy your own creature.
-------------------
Chapter 10
wretched
You have made me wretched beyond expression.
-------------------
Chapter 10
creature
On you it rests, whether I quit for ever the neighbourhood of man and lead a harmless life, or become the scourge of your fellow creatures and the author of your own speedy ruin.”
-------------------
Chapter 10
creature
For the first time, also, I felt what the duties of a creator towards his creature were, and that I ought to render him happy before I complained of his wickedness.
-------------------
Chapter 11
wretch
I was a poor, helpless, miserable wretch; I knew, and could distinguish, nothing; but feeling pain invade me on all sides, I sat down and wept.
-------------------
Chapter 11
wretched
The whole village was roused; some fled, some attacked me, until, grievously bruised by stones and many other kinds of missile weapons, I escaped to the open country and fearfully took refuge in a low hovel, quite bare, and making a wretched appearance after the palaces I had beheld in the village.
-------------------
Chapter 11
creature
I ate my breakfast with pleasure and was about to remove a plank to procure myself a little water when I heard a step, and looking through a small chink, I beheld a young creature, with a pail on her head, passing before my hovel.
-------------------
Chapter 11
wretch
It was a lovely sight, even to me, poor wretch who had never beheld aught beautiful before.
-------------------
Chapter 11
creature
He played a sweet mournful air which I perceived drew tears from the eyes of his amiable companion, of which the old man took no notice, until she sobbed audibly; he then pronounced a few sounds, and the fair creature, leaving her work, knelt at his feet.
-------------------
Chapter 11
creature
Nothing could exceed in beauty the contrast between these two excellent creatures.
-------------------
Chapter 12
creature
If such lovely creatures were miserable, it was less strange that I, an imperfect and solitary being, should be wretched.
-------------------
Chapter 12
wretched
If such lovely creatures were miserable, it was less strange that I, an imperfect and solitary being, should be wretched.
-------------------
Chapter 12
creature
“My thoughts now became more active, and I longed to discover the motives and feelings of these lovely creatures; I was inquisitive to know why Felix appeared so miserable and Agatha so sad.
-------------------
Chapter 12
wretch
I thought (foolish wretch!) that it might be in my power to restore happiness to these deserving people.
-------------------
Chapter 13
creature
I learned that the possessions most esteemed by your fellow creatures were high and unsullied descent united with riches.
-------------------
Chapter 13
wretch
Miserable, unhappy wretch!
-------------------
Chapter 15
wretched
I learned from Werter’s imaginations despondency and gloom, but Plutarch taught me high thoughts; he elevated me above the wretched sphere of my own reflections, to admire and love the heroes of past ages.
-------------------
Chapter 15
creature
It moved every feeling of wonder and awe that the picture of an omnipotent God warring with his creatures was capable of exciting.
-------------------
Chapter 15
creature
He had come forth from the hands of God a perfect creature, happy and prosperous, guarded by the especial care of his Creator; he was allowed to converse with and acquire knowledge from beings of a superior nature, but I was wretched, helpless, and alone.
-------------------
Chapter 15
wretched
He had come forth from the hands of God a perfect creature, happy and prosperous, guarded by the especial care of his Creator; he was allowed to converse with and acquire knowledge from beings of a superior nature, but I was wretched, helpless, and alone.
-------------------
Chapter 15
wretched
Increase of knowledge only discovered to me more clearly what a wretched outcast
-------------------
Chapter 15
creature
“I endeavoured to crush these fears and to fortify myself for the trial which in a few months I resolved to undergo; and sometimes I allowed my thoughts, unchecked by reason, to ramble in the fields of Paradise, and dared to fancy amiable and lovely creatures sympathising with my feelings and cheering my gloom; their angelic countenances breathed smiles of consolation.
-------------------
Chapter 15
creature
The more I saw of them, the greater became my desire to claim their protection and kindness; my heart yearned to be known and loved by these amiable creatures; to see their sweet looks directed towards me with affection was the utmost limit of my ambition.
-------------------
Chapter 15
creature
I am an unfortunate and deserted creature, I look around and I have no relation or friend upon earth.
-------------------
Chapter 15
creature
“‘They are kind—they are the most excellent creatures in the world; but, unfortunately, they are prejudiced against me.
-------------------
Chapter 15
creature
I am poor and an exile, but it will afford me true pleasure to be in any way serviceable to a human creature.’
-------------------
Chapter 15
creature
You raise me from the dust by this kindness; and I trust that, by your aid, I shall not be driven from the society and sympathy of your fellow creatures.’
-------------------
Chapter 16
creature
Suddenly, as I gazed on him, an idea seized me that this little creature was unprejudiced and had lived too short a time to have imbibed a horror of deformity.
-------------------
Chapter 16
wretch
Ugly wretch!
-------------------
Chapter 16
creature
For a few moments I gazed with delight on her dark eyes, fringed by deep lashes, and her lovely lips; but presently my rage returned; I remembered that I was for ever deprived of the delights that such beautiful creatures could bestow and that she whose resemblance I contemplated would, in regarding me, have changed that air of divine benignity to one expressive of disgust and affright.
-------------------
Chapter 17
creature
If any being felt emotions of benevolence towards me, I should return them a hundred and a hundredfold; for that one creature’s sake I would make peace with the whole kind!
-------------------
Chapter 17
creature
What I ask of you is reasonable and moderate; I demand a creature of another sex, but as hideous as myself; the gratification is small, but it is all that I can receive, and it shall content me.
-------------------
Chapter 17
creature
His tale and the feelings he now expressed proved him to be a creature of fine sensations, and did I not as his maker owe him all the portion of happiness that it was in my power to bestow?
-------------------
Chapter 17
creature
His power and threats were not omitted in my calculations; a creature who could exist in the ice-caves of the glaciers and hide himself from pursuit among the ridges of inaccessible precipices was a being possessing faculties it would be vain to cope with.
-------------------
Chapter 17
creature
After a long pause of reflection I concluded that the justice due both to him and my fellow creatures demanded of me that I should comply with his request.
-------------------
Chapter 18
creature
But through the whole period during which I was the slave of my creature I allowed myself to be governed by the impulses of the moment; and my present sensations strongly intimated that the fiend would follow me and exempt my family from the danger of his machinations.
-------------------
Chapter 18
wretch
I, a miserable wretch, haunted by a curse that shut up every avenue to enjoyment.
-------------------
Chapter 19
creature
I feared to wander from the sight of my fellow creatures lest when alone he should come to claim his companion.
-------------------
Chapter 20
creature
They might even hate each other; the creature who already lived loathed his own deformity, and might he not conceive a greater abhorrence for it when it came before his eyes in the female form?
-------------------
Chapter 20
wretch
The wretch saw me destroy the creature on whose future existence he depended for happiness, and with a howl of devilish despair and revenge, withdrew.
-------------------
Chapter 20
creature
The wretch saw me destroy the creature on whose future existence he depended for happiness, and with a howl of devilish despair and revenge, withdrew.
-------------------
Chapter 20
wretch
Presently I heard the sound of footsteps along the passage; the door opened, and the wretch whom I dreaded appeared.
-------------------
Chapter 20
wretched
Remember that I have power; you believe yourself miserable, but I can make you so wretched that the light of day will be hateful to you.
-------------------
Chapter 20
creature
I left the house, the horrid scene of the last night’s contention, and walked on the beach of the sea, which I almost regarded as an insuperable barrier between me and my fellow creatures; nay, a wish that such should prove the fact stole across me.
-------------------
Chapter 20
creature
The remains of the half-finished creature, whom I had destroyed, lay scattered on the floor, and I almost felt as if I had mangled the living flesh of a human being.
-------------------
Chapter 20
creature
I felt as if I was about the commission of a dreadful crime and avoided with shuddering anxiety any encounter with my fellow creatures.
-------------------
Chapter 21
wretched
But I was doomed to live and in two months found myself as awaking from a dream, in a prison, stretched on a wretched bed, surrounded by gaolers, turnkeys, bolts, and all the miserable apparatus of a dungeon.
-------------------
Chapter 21
wretched
He had caused the best room in the prison to be prepared for me (wretched indeed was the best); and it was he who had provided a physician and a nurse.
-------------------
Chapter 21
creature
It is true, he seldom came to see me, for although he ardently desired to relieve the sufferings of every human creature, he did not wish to be present at the agonies and miserable ravings of a murderer.
-------------------
Chapter 21
wretched
“What a place is this that you inhabit, my son!” said he, looking mournfully at the barred windows and wretched appearance of the room.
-------------------
Chapter 22
creature
They were my brethren, my fellow beings, and I felt attracted even to the most repulsive among them, as to creatures of an angelic nature and celestial mechanism.
-------------------
Chapter 22
wretch
Human beings, their feelings and passions, would indeed be degraded if such a wretch as I felt pride.
-------------------
Chapter 22
wretch
I avoided explanation and maintained a continual silence concerning the wretch I had created.
-------------------
Chapter 22
creature

In [23]:
with pd.ExcelWriter('../outputs/wretched-creatures.xlsx') as writer:
    maria_wretch_df.to_excel(writer, sheet_name='maria')
    frankenstein_wretch_df.to_excel(writer, sheet_name='frankenstein')